# Generated by Django 4.0.4 on 2022-04-28 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='messsge',
            new_name='message',
        ),
    ]
